//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyFeedSampleApp.PropertyFeed {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", ConfigurationName="PropertyFeed.DataReceiverServiceSoap")]
    public interface DataReceiverServiceSoap {
        
        // CODEGEN: Generating message contract since message OTARequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://VacationRoost.GatewayServices.DataReceiverService/OTARequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PropertyFeedSampleApp.PropertyFeed.OTARequestResponse OTARequest(PropertyFeedSampleApp.PropertyFeed.OTARequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://VacationRoost.GatewayServices.DataReceiverService/OTARequest", ReplyAction="*")]
        System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.OTARequestResponse> OTARequestAsync(PropertyFeedSampleApp.PropertyFeed.OTARequestRequest request);
        
        // CODEGEN: Generating message contract since message DataExtractRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://VacationRoost.GatewayServices.DataReceiverService/DataExtract", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PropertyFeedSampleApp.PropertyFeed.DataExtractResponse DataExtract(PropertyFeedSampleApp.PropertyFeed.DataExtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://VacationRoost.GatewayServices.DataReceiverService/DataExtract", ReplyAction="*")]
        System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.DataExtractResponse> DataExtractAsync(PropertyFeedSampleApp.PropertyFeed.DataExtractRequest request);
        
        // CODEGEN: Generating message contract since message GetValidRentalUnitIdsForExtractRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://VacationRoost.GatewayServices.DataReceiverService/GetValidRentalUnitIdsFor" +
            "Extract", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractResponse GetValidRentalUnitIdsForExtract(PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://VacationRoost.GatewayServices.DataReceiverService/GetValidRentalUnitIdsFor" +
            "Extract", ReplyAction="*")]
        System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractResponse> GetValidRentalUnitIdsForExtractAsync(PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OTARequest", WrapperNamespace="http://VacationRoost.GatewayServices.DataReceiverService", IsWrapped=true)]
    public partial class OTARequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService")]
        public PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=0)]
        public string otaRequest;
        
        public OTARequestRequest() {
        }
        
        public OTARequestRequest(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string otaRequest) {
            this.AuthHeader = AuthHeader;
            this.otaRequest = otaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OTARequestResponse", WrapperNamespace="http://VacationRoost.GatewayServices.DataReceiverService", IsWrapped=true)]
    public partial class OTARequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=0)]
        public string OTARequestResult;
        
        public OTARequestResponse() {
        }
        
        public OTARequestResponse(string OTARequestResult) {
            this.OTARequestResult = OTARequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataExtract", WrapperNamespace="http://VacationRoost.GatewayServices.DataReceiverService", IsWrapped=true)]
    public partial class DataExtractRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService")]
        public PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=0)]
        public string extractType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=1)]
        public string gatewayProviderType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=2)]
        public string supplierId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=3)]
        public string rentalUnitId;
        
        public DataExtractRequest() {
        }
        
        public DataExtractRequest(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string extractType, string gatewayProviderType, string supplierId, string rentalUnitId) {
            this.AuthHeader = AuthHeader;
            this.extractType = extractType;
            this.gatewayProviderType = gatewayProviderType;
            this.supplierId = supplierId;
            this.rentalUnitId = rentalUnitId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataExtractResponse", WrapperNamespace="http://VacationRoost.GatewayServices.DataReceiverService", IsWrapped=true)]
    public partial class DataExtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=0)]
        public string DataExtractResult;
        
        public DataExtractResponse() {
        }
        
        public DataExtractResponse(string DataExtractResult) {
            this.DataExtractResult = DataExtractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValidRentalUnitIdsForExtract", WrapperNamespace="http://VacationRoost.GatewayServices.DataReceiverService", IsWrapped=true)]
    public partial class GetValidRentalUnitIdsForExtractRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService")]
        public PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=0)]
        public string gatewayProviderType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=1)]
        public string supplierId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=2)]
        public bool sendSupplierIdsOnly;
        
        public GetValidRentalUnitIdsForExtractRequest() {
        }
        
        public GetValidRentalUnitIdsForExtractRequest(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string gatewayProviderType, string supplierId, bool sendSupplierIdsOnly) {
            this.AuthHeader = AuthHeader;
            this.gatewayProviderType = gatewayProviderType;
            this.supplierId = supplierId;
            this.sendSupplierIdsOnly = sendSupplierIdsOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValidRentalUnitIdsForExtractResponse", WrapperNamespace="http://VacationRoost.GatewayServices.DataReceiverService", IsWrapped=true)]
    public partial class GetValidRentalUnitIdsForExtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://VacationRoost.GatewayServices.DataReceiverService", Order=0)]
        public long[] GetValidRentalUnitIdsForExtractResult;
        
        public GetValidRentalUnitIdsForExtractResponse() {
        }
        
        public GetValidRentalUnitIdsForExtractResponse(long[] GetValidRentalUnitIdsForExtractResult) {
            this.GetValidRentalUnitIdsForExtractResult = GetValidRentalUnitIdsForExtractResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataReceiverServiceSoapChannel : PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataReceiverServiceSoapClient : System.ServiceModel.ClientBase<PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap>, PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap {
        
        public DataReceiverServiceSoapClient() {
        }
        
        public DataReceiverServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataReceiverServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataReceiverServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataReceiverServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PropertyFeedSampleApp.PropertyFeed.OTARequestResponse PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap.OTARequest(PropertyFeedSampleApp.PropertyFeed.OTARequestRequest request) {
            return base.Channel.OTARequest(request);
        }
        
        public string OTARequest(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string otaRequest1) {
            PropertyFeedSampleApp.PropertyFeed.OTARequestRequest inValue = new PropertyFeedSampleApp.PropertyFeed.OTARequestRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.otaRequest = otaRequest1;
            PropertyFeedSampleApp.PropertyFeed.OTARequestResponse retVal = ((PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap)(this)).OTARequest(inValue);
            return retVal.OTARequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.OTARequestResponse> PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap.OTARequestAsync(PropertyFeedSampleApp.PropertyFeed.OTARequestRequest request) {
            return base.Channel.OTARequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.OTARequestResponse> OTARequestAsync(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string otaRequest) {
            PropertyFeedSampleApp.PropertyFeed.OTARequestRequest inValue = new PropertyFeedSampleApp.PropertyFeed.OTARequestRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.otaRequest = otaRequest;
            return ((PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap)(this)).OTARequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PropertyFeedSampleApp.PropertyFeed.DataExtractResponse PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap.DataExtract(PropertyFeedSampleApp.PropertyFeed.DataExtractRequest request) {
            return base.Channel.DataExtract(request);
        }
        
        public string DataExtract(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string extractType, string gatewayProviderType, string supplierId, string rentalUnitId) {
            PropertyFeedSampleApp.PropertyFeed.DataExtractRequest inValue = new PropertyFeedSampleApp.PropertyFeed.DataExtractRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.extractType = extractType;
            inValue.gatewayProviderType = gatewayProviderType;
            inValue.supplierId = supplierId;
            inValue.rentalUnitId = rentalUnitId;
            PropertyFeedSampleApp.PropertyFeed.DataExtractResponse retVal = ((PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap)(this)).DataExtract(inValue);
            return retVal.DataExtractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.DataExtractResponse> PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap.DataExtractAsync(PropertyFeedSampleApp.PropertyFeed.DataExtractRequest request) {
            return base.Channel.DataExtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.DataExtractResponse> DataExtractAsync(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string extractType, string gatewayProviderType, string supplierId, string rentalUnitId) {
            PropertyFeedSampleApp.PropertyFeed.DataExtractRequest inValue = new PropertyFeedSampleApp.PropertyFeed.DataExtractRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.extractType = extractType;
            inValue.gatewayProviderType = gatewayProviderType;
            inValue.supplierId = supplierId;
            inValue.rentalUnitId = rentalUnitId;
            return ((PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap)(this)).DataExtractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractResponse PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap.GetValidRentalUnitIdsForExtract(PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractRequest request) {
            return base.Channel.GetValidRentalUnitIdsForExtract(request);
        }
        
        public long[] GetValidRentalUnitIdsForExtract(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string gatewayProviderType, string supplierId, bool sendSupplierIdsOnly) {
            PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractRequest inValue = new PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.gatewayProviderType = gatewayProviderType;
            inValue.supplierId = supplierId;
            inValue.sendSupplierIdsOnly = sendSupplierIdsOnly;
            PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractResponse retVal = ((PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap)(this)).GetValidRentalUnitIdsForExtract(inValue);
            return retVal.GetValidRentalUnitIdsForExtractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractResponse> PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap.GetValidRentalUnitIdsForExtractAsync(PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractRequest request) {
            return base.Channel.GetValidRentalUnitIdsForExtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractResponse> GetValidRentalUnitIdsForExtractAsync(PropertyFeedSampleApp.PropertyFeed.AuthHeader AuthHeader, string gatewayProviderType, string supplierId, bool sendSupplierIdsOnly) {
            PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractRequest inValue = new PropertyFeedSampleApp.PropertyFeed.GetValidRentalUnitIdsForExtractRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.gatewayProviderType = gatewayProviderType;
            inValue.supplierId = supplierId;
            inValue.sendSupplierIdsOnly = sendSupplierIdsOnly;
            return ((PropertyFeedSampleApp.PropertyFeed.DataReceiverServiceSoap)(this)).GetValidRentalUnitIdsForExtractAsync(inValue);
        }
    }
}
